version: '3.8'

services:
  db:
    image: docker.io/library/postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: joseph
      POSTGRES_USER: joseph
      POSTGRES_PASSWORD: egypt-governor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
