spring:
  application:
    name: joseph-api
  datasource:
    url: jdbc:postgresql://localhost:5555/joseph
    username: joseph
    password: egypt-governor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

application:
  info:
    title: Joseph API
    version: v1.0.0
    description: API para gestão de finanças pessoais.
