spring:
  application:
    name: joseph
  datasource:
    url: jdbc:postgresql://localhost:5555/joseph
    username: joseph
    password: egypt-governor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

info:
  app:
    version: '@project.version@'
