spring:
  application:
    name: joseph-api
  datasource:
    url: jdbc:postgresql://localhost:5555/joseph
    username: joseph
    password: egypt-governor
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
    info:
      title: Joseph API
      description: API para gestão de finanças pessoais
      version: v1.0.0
  swagger-ui:
    path: /docs
