name: PR Checks

on:
  pull_request:
    branch: master

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run ktlint
        run: ./gradlew ktlintCheck

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run tests
        run: ./gradlew test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      - name: Run Jacoco coverage
        run: ./gradlew test jacocoTestReport
      - name: Check coverage percentage
        run: |
          COUNTER_LINE=$(grep -m1 '<counter type="INSTRUCTION"' build/reports/jacoco/test/jacocoTestReport.xml)
          MISSED=$(echo "$COUNTER_LINE" | sed -n 's/.*missed="\([0-9]\+\)".*/\1/p')
          COVERED=$(echo "$COUNTER_LINE" | sed -n 's/.*covered="\([0-9]\+\)".*/\1/p')
          if [ -z "$MISSED" ] || [ -z "$COVERED" ]; then
            echo "Could not extract coverage data."
            exit 1
          fi
          TOTAL=$((MISSED + COVERED))
          if [ "$TOTAL" -gt 0 ]; then
            PERCENT=$((COVERED * 100 / TOTAL))
          else
            PERCENT=0
          fi
          echo "Coverage percentage: $PERCENT%"
          if [ "$PERCENT" -lt 80 ]; then
            echo "Coverage below 80%. Actual: $PERCENT%"
            exit 1
          fi

  conventional-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .github/commitlint.config.js
