name: Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: false
        default: 'master'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch || 'master' }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release and plugins
        run: |
          npm install -g semantic-release @semantic-release/github @semantic-release/release-notes-generator @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/changelog @semantic-release/git

      - name: Ensure update-version.sh is executable
        run: chmod +x scripts/update-version.sh

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          semantic-release

      - name: Create Pull Request with version and changelog updates
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(release): atualiza CHANGELOG, build.gradle.kts e application.yml [skip ci]"
          title: "chore(release): atualiza arquivos de versão e changelog"
          body: "Este PR atualiza o CHANGELOG.md, build.gradle.kts e application.yml com a nova versão gerada pelo release automatizado."
          branch: release/auto-version-update
          base: master
          add-paths: |
            CHANGELOG.md
            build.gradle.kts
            src/main/resources/application.yml
          delete-branch: true
